"""
IPL Oracle Backend — FastAPI application entry point.

Run with:
    uv run python run.py
    OR
    uv run uvicorn run:app --reload --port 8000
"""

from __future__ import annotations

import os

import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router as api_router
from app.middleware.disclaimer import DisclaimerMiddleware

# Load environment variables
load_dotenv()

# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

def create_app() -> FastAPI:
    """Create and configure the FastAPI application."""

    app = FastAPI(
        title="IPL Oracle",
        description=(
            "A MiroFish-style swarm intelligence engine for IPL cricket match prediction. "
            "Spawns autonomous agents for every match entity and runs parallel simulations. "
            "\n\n⚠️ SIMULATION ONLY — Not betting advice. Full terms: LICENSE.md"
        ),
        version="4.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_tags=[
            {"name": "schedule", "description": "IPL 2026 match schedule"},
            {"name": "simulation", "description": "Match simulation engine"},
            {"name": "agents", "description": "Agent profiles and interviews"},
        ],
    )

    # CORS — allow frontend dev server
    frontend_url = os.getenv("FRONTEND_URL", "http://localhost:5173")
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[
            frontend_url,
            "http://localhost:5173",
            "http://localhost:3000",
            "http://127.0.0.1:5173",
        ],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Disclaimer middleware — injects disclaimer header on all /api/ routes
    app.add_middleware(DisclaimerMiddleware)

    # Mount API router
    app.include_router(api_router, prefix="/api")

    # Refresh schedule from web at startup
    @app.on_event("startup")
    async def _refresh_schedule() -> None:
        from app.api.routes import schedule_manager
        await schedule_manager.refresh()

    # Health check
    @app.get("/health")
    async def health() -> dict:
        return {
            "status": "ok",
            "service": "ipl-oracle-backend",
            "version": "4.0.0",
            "mode": "Week4-Hybrid-LLM",
        }

    # Root
    @app.get("/")
    async def root() -> dict:
        return {
            "message": "IPL Oracle API",
            "version": "4.0.0",
            "docs": "/docs",
            "disclaimer": (
                "⚠️ SIMULATION ONLY: Generated by an AI swarm engine for research and entertainment. "
                "Not betting advice. Not a guarantee of outcomes. "
                "Repo owner accepts no responsibility for personal or financial losses. "
                "Full terms: LICENSE.md"
            ),
        }

    return app


# ---------------------------------------------------------------------------
# App instance (for uvicorn import and direct run)
# ---------------------------------------------------------------------------

app = create_app()


if __name__ == "__main__":
    host = os.getenv("APP_HOST", "0.0.0.0")
    port = int(os.getenv("APP_PORT", "8000"))
    env = os.getenv("APP_ENV", "development")
    reload = env == "development"

    print(f"Starting IPL Oracle backend on {host}:{port} (env={env})")
    print("[!] SIMULATION ONLY - Not betting advice")

    uvicorn.run(
        "run:app",
        host=host,
        port=port,
        reload=reload,
        log_level="info",
    )
