<template>
  <!-- Non-dismissible disclaimer bar — MANDATORY on every page per project spec -->
  <div class="disclaimer-bar" role="alert" aria-live="polite">
    <div class="disclaimer-inner">
      <span class="disclaimer-icon">⚠️</span>
      <span class="disclaimer-text">
        <strong>SIMULATION ONLY:</strong>
        Generated by an AI swarm engine for research and entertainment.
        Not betting advice. Not a guarantee of outcomes.
        Repo owner accepts no responsibility for personal or financial losses.
        <a href="/LICENSE.md" target="_blank" rel="noopener">Full terms: LICENSE.md</a>
      </span>
    </div>
  </div>
</template>

<script setup>
// This component is intentionally non-dismissible.
// It renders the mandatory disclaimer on every page.
// Do not add a close button.
</script>

<style scoped>
.disclaimer-bar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  background: #1a0a00;
  border-bottom: 2px solid #ff9800;
  padding: 0.4rem 1rem;
}

.disclaimer-inner {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.disclaimer-icon {
  font-size: 0.9rem;
  flex-shrink: 0;
}

.disclaimer-text {
  font-size: 0.75rem;
  color: #ffcc80;
  line-height: 1.4;
}

.disclaimer-text strong {
  color: #ff9800;
}

.disclaimer-text a {
  color: #ff9800;
  text-decoration: underline;
}

.disclaimer-text a:hover {
  color: #ffcc80;
}
</style>
