"""
LLMClient — Multi-provider LLM client for hybrid-mode agent decisions.

Supported providers (set LLM_PROVIDER in .env):
  anthropic  — Anthropic claude-sonnet-4-6          (requires ANTHROPIC_API_KEY)
  openai     — OpenAI gpt-4o                         (requires OPENAI_API_KEY)
  gemini     — Google Gemini via OpenAI-compat layer  (requires GEMINI_API_KEY)
  local      — Any OpenAI-compatible local server     (Ollama, LM Studio, vLLM, etc.)
               Set LOCAL_LLM_BASE_URL + LOCAL_LLM_MODEL in .env

Auto-detection: if LLM_PROVIDER is not set, the first key found in env is used.
Priority: anthropic → openai → gemini → local.

Hybrid mode trigger: pressure_index >= LLM_PRESSURE_THRESHOLD (default 0.85).
Falls back to None (probabilistic path) on any error or when disabled.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "⚠️ SIMULATION ONLY: Generated by an AI swarm engine for research and entertainment. "
    "Not betting advice. Not a guarantee of outcomes. "
    "Repo owner accepts no responsibility for personal or financial losses. "
    "Full terms: LICENSE.md"
)

LLM_PRESSURE_THRESHOLD = float(os.getenv("LLM_PRESSURE_THRESHOLD", "0.65"))

# Default model IDs per provider (overridden by ANTHROPIC_MODEL, OPENAI_MODEL, etc.)
_DEFAULT_MODELS: dict[str, str] = {
    "anthropic": os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-6"),
    "openai": os.getenv("OPENAI_MODEL", "gpt-4o"),
    "gemini": os.getenv("GEMINI_MODEL", "gemini-2.0-flash"),
    "local": os.getenv("LOCAL_LLM_MODEL", "llama3.2"),
}

# Gemini's OpenAI-compatible endpoint
_GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai/"


def _detect_provider() -> str | None:
    """Return the first provider whose key is present in the environment."""
    if os.getenv("ANTHROPIC_API_KEY"):
        return "anthropic"
    if os.getenv("OPENAI_API_KEY"):
        return "openai"
    if os.getenv("GEMINI_API_KEY"):
        return "gemini"
    # Local is always available if configured; only include if base URL differs from default
    if os.getenv("LOCAL_LLM_BASE_URL"):
        return "local"
    return None


class _AnthropicBackend:
    """Thin async wrapper around the Anthropic SDK."""

    def __init__(self, api_key: str, model: str) -> None:
        import anthropic
        self._client = anthropic.AsyncAnthropic(api_key=api_key)
        self._model = model

    async def complete(
        self, system_prompt: str, user_prompt: str, max_tokens: int
    ) -> str:
        message = await self._client.messages.create(
            model=self._model,
            max_tokens=max_tokens,
            system=f"{system_prompt}\n\n{DISCLAIMER}",
            messages=[{"role": "user", "content": user_prompt}],
        )
        return message.content[0].text


class _OpenAICompatBackend:
    """
    Async wrapper for any OpenAI-compatible API.

    Covers: OpenAI, Gemini (via /v1beta/openai/ endpoint), and local servers
    (Ollama, LM Studio, vLLM) — all accept the same openai.AsyncOpenAI interface.
    """

    def __init__(self, api_key: str, model: str, base_url: str | None = None) -> None:
        from openai import AsyncOpenAI
        kwargs: dict[str, Any] = {"api_key": api_key}
        if base_url:
            kwargs["base_url"] = base_url
        self._client = AsyncOpenAI(**kwargs)
        self._model = model

    async def complete(
        self, system_prompt: str, user_prompt: str, max_tokens: int
    ) -> str:
        response = await self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": f"{system_prompt}\n\n{DISCLAIMER}"},
                {"role": "user", "content": user_prompt},
            ],
        )
        content = response.choices[0].message.content or ""
        return content


def _build_backend(provider: str, model: str) -> _AnthropicBackend | _OpenAICompatBackend:
    """Instantiate the correct backend for the given provider."""
    if provider == "anthropic":
        api_key = os.getenv("ANTHROPIC_API_KEY", "")
        return _AnthropicBackend(api_key=api_key, model=model)

    if provider == "openai":
        api_key = os.getenv("OPENAI_API_KEY", "")
        return _OpenAICompatBackend(api_key=api_key, model=model)

    if provider == "gemini":
        api_key = os.getenv("GEMINI_API_KEY", "")
        return _OpenAICompatBackend(
            api_key=api_key, model=model, base_url=_GEMINI_BASE_URL
        )

    if provider == "local":
        base_url = os.getenv("LOCAL_LLM_BASE_URL", "http://localhost:11434/v1")
        api_key = os.getenv("LOCAL_LLM_API_KEY", "ollama")
        return _OpenAICompatBackend(api_key=api_key, model=model, base_url=base_url)

    raise ValueError(f"Unknown LLM provider: {provider!r}")


class LLMClient:
    """
    Provider-agnostic LLM client for agent think() calls.

    Provider resolution order:
    1. LLM_PROVIDER env var (explicit)
    2. Auto-detect from available API keys (anthropic → openai → gemini → local)
    3. Disabled (all calls return None → probabilistic fallback)

    Model resolution:
    1. LLM_MODEL env var (explicit override)
    2. Provider default (see _DEFAULT_MODELS)
    """

    def __init__(self) -> None:
        explicit_provider = os.getenv("LLM_PROVIDER", "").strip().lower()
        self._provider = explicit_provider or _detect_provider()
        self._enabled = False
        self._backend: _AnthropicBackend | _OpenAICompatBackend | None = None

        if not self._provider:
            logger.info(
                "LLMClient: no provider configured — hybrid mode disabled. "
                "Set LLM_PROVIDER (anthropic|openai|gemini|local) to enable."
            )
            return

        explicit_model = os.getenv("LLM_MODEL", "").strip()
        self._model = explicit_model or _DEFAULT_MODELS.get(self._provider, "")

        try:
            self._backend = _build_backend(self._provider, self._model)
            self._enabled = True
            logger.info(
                "LLMClient: enabled — provider=%s model=%s threshold=%.2f",
                self._provider,
                self._model,
                LLM_PRESSURE_THRESHOLD,
            )
        except ImportError as exc:
            logger.warning(
                "LLMClient: required package missing for provider %r (%s) — disabled",
                self._provider,
                exc,
            )
        except Exception as exc:
            logger.warning("LLMClient: init failed (%s) — disabled", exc)

    async def think(
        self,
        system_prompt: str,
        user_prompt: str,
        context: dict[str, Any] | None = None,
        max_tokens: int = 2048,
    ) -> str | None:
        """
        Call the LLM for a high-leverage decision.

        Args:
            system_prompt: Agent persona and instructions
            user_prompt: The specific decision prompt
            context: Structured context dict appended to user_prompt as JSON
            max_tokens: Max response tokens

        Returns:
            LLM response string, or None on error / disabled.
        """
        if not self._enabled or self._backend is None:
            return None

        full_user_prompt = user_prompt
        if context:
            full_user_prompt = (
                f"{user_prompt}\n\n"
                f"Match context:\n{json.dumps(context, indent=2, default=str)}"
            )

        try:
            return await self._backend.complete(system_prompt, full_user_prompt, max_tokens)
        except Exception as exc:
            print(f"[LLM ERROR] provider={self._provider} model={self._model}: {exc}")
            logger.warning(
                "LLMClient.think failed (provider=%s): %s — falling back to probabilistic",
                self._provider,
                exc,
            )
            return None

    def is_enabled(self) -> bool:
        """Return True if LLM calls are enabled."""
        return self._enabled

    def should_use_llm(self, pressure_index: float) -> bool:
        """Return True if pressure is high enough and a provider is configured."""
        return self._enabled and pressure_index >= LLM_PRESSURE_THRESHOLD

    @property
    def provider(self) -> str | None:
        return self._provider

    @property
    def model(self) -> str:
        return self._model if self._enabled else ""


# Singleton instance — initialised once at import time
llm_client = LLMClient()
