"""
ReportAgent — Post-simulation synthesis agent.

Aggregates results from all 100 simulations into a final report with:
- Win probability + confidence interval
- Score distribution data
- Key player matchup analysis
- Impact Player analysis
- Toss recommendation
- Bold scoreline prediction

Week 1: Basic aggregation, no LLM ReACT loop yet.
Week 4: Full ReACT loop with tool-calling.

DISCLAIMER: Every output from this agent MUST include the mandatory disclaimer text.
"""

from __future__ import annotations

import statistics
from typing import Any

from .base_agent import BaseAgent

DISCLAIMER = (
    "⚠️ SIMULATION ONLY: Generated by an AI swarm engine for research and entertainment. "
    "Not betting advice. Not a guarantee of outcomes. "
    "Repo owner accepts no responsibility for personal or financial losses. "
    "Full terms: LICENSE.md"
)


class ReportAgent(BaseAgent):
    """
    Post-simulation report synthesis agent.

    Runs once after all simulations complete. Produces the final prediction report.
    IMPORTANT: Every output must include the DISCLAIMER text.
    """

    def __init__(
        self,
        simulation_id: str,
        run_id: str | None = None,
    ) -> None:
        profile = {
            "simulation_id": simulation_id,
            "disclaimer": DISCLAIMER,
        }
        super().__init__(agent_type="report", profile=profile, run_id=run_id)
        self._simulation_id = simulation_id

    def generate_report(
        self,
        team1: str,
        team2: str,
        sim_results: list[dict[str, Any]],
        venue: str,
        match_state: str,
    ) -> dict[str, Any]:
        """
        Generate the final prediction report from simulation results.

        Args:
            team1: First team name
            team2: Second team name
            sim_results: List of simulation result dicts from MatchEngine
            venue: Venue name
            match_state: Match state when simulation was run (FUTURE/IMMINENT/LIVE)

        Returns:
            Report dict with win probabilities, score distributions, and prediction.
        """
        if not sim_results:
            return self._empty_report(team1, team2, venue)

        n = len(sim_results)

        # Count wins
        team1_wins = sum(1 for r in sim_results if r.get("winner") == team1)
        team2_wins = sum(1 for r in sim_results if r.get("winner") == team2)
        no_result = n - team1_wins - team2_wins

        team1_win_pct = team1_wins / n
        team2_win_pct = team2_wins / n

        # Wilson score confidence interval (95%)
        team1_ci = self._wilson_ci(team1_wins, n)
        team2_ci = self._wilson_ci(team2_wins, n)

        # Score distributions
        team1_scores = [r.get("team1_score", 0) for r in sim_results if r.get("team1_score")]
        team2_scores = [r.get("team2_score", 0) for r in sim_results if r.get("team2_score")]

        team1_score_stats = self._score_stats(team1_scores) if team1_scores else {}
        team2_score_stats = self._score_stats(team2_scores) if team2_scores else {}

        # Predicted winner
        if team1_win_pct > team2_win_pct:
            predicted_winner = team1
            predicted_winner_confidence = team1_win_pct
        else:
            predicted_winner = team2
            predicted_winner_confidence = team2_win_pct

        # Confidence label
        if predicted_winner_confidence >= 0.70:
            confidence_label = "HIGH"
        elif predicted_winner_confidence >= 0.55:
            confidence_label = "MEDIUM"
        else:
            confidence_label = "LOW"

        # Bold scoreline prediction (mode of winning scores)
        predicted_score = None
        if predicted_winner == team1 and team1_score_stats:
            predicted_score = team1_score_stats.get("median")
        elif team2_score_stats:
            predicted_score = team2_score_stats.get("median")

        report = {
            "disclaimer": DISCLAIMER,
            "simulation_id": self._simulation_id,
            "match_state_at_simulation": match_state,
            "venue": venue,
            "teams": {
                "team1": team1,
                "team2": team2,
            },
            "simulation_count": n,
            "win_probability": {
                team1: {
                    "wins": team1_wins,
                    "win_pct": round(team1_win_pct * 100, 1),
                    "confidence_interval_95": {
                        "lower": round(team1_ci[0] * 100, 1),
                        "upper": round(team1_ci[1] * 100, 1),
                    },
                },
                team2: {
                    "wins": team2_wins,
                    "win_pct": round(team2_win_pct * 100, 1),
                    "confidence_interval_95": {
                        "lower": round(team2_ci[0] * 100, 1),
                        "upper": round(team2_ci[1] * 100, 1),
                    },
                },
                "no_result": no_result,
            },
            "score_distribution": {
                team1: team1_score_stats,
                team2: team2_score_stats,
                "histogram_data": {
                    team1: self._build_histogram(team1_scores),
                    team2: self._build_histogram(team2_scores),
                },
            },
            "prediction": {
                "winner": predicted_winner,
                "confidence_pct": round(predicted_winner_confidence * 100, 1),
                "confidence_label": confidence_label,
                "predicted_score": predicted_score,
                "summary": (
                    f"{predicted_winner} predicted to win with "
                    f"{predicted_winner_confidence*100:.0f}% probability "
                    f"across {n} simulations. "
                    f"Predicted score: ~{predicted_score}"
                ) if predicted_score else f"{predicted_winner} predicted to win",
            },
            "caveats": self._get_caveats(match_state),
        }

        self.log_decision(
            "report_generated",
            predicted_winner,
            reasoning=f"Win probability: {predicted_winner_confidence:.1%} from {n} sims",
            context={"simulations": n, "team1_wins": team1_wins, "team2_wins": team2_wins},
        )

        return report

    @staticmethod
    def _wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
        """Wilson score confidence interval for a proportion."""
        if n == 0:
            return (0.0, 1.0)
        p_hat = k / n
        denominator = 1 + z**2 / n
        centre = (p_hat + z**2 / (2 * n)) / denominator
        margin = (z * (p_hat * (1 - p_hat) / n + z**2 / (4 * n**2)) ** 0.5) / denominator
        return (max(0.0, centre - margin), min(1.0, centre + margin))

    @staticmethod
    def _score_stats(scores: list[int]) -> dict[str, float]:
        """Compute descriptive stats for a score distribution."""
        if not scores:
            return {}
        return {
            "min": min(scores),
            "max": max(scores),
            "mean": round(statistics.mean(scores), 1),
            "median": round(statistics.median(scores), 0),
            "stdev": round(statistics.stdev(scores), 1) if len(scores) > 1 else 0.0,
            "p25": round(sorted(scores)[len(scores) // 4], 0),
            "p75": round(sorted(scores)[3 * len(scores) // 4], 0),
        }

    @staticmethod
    def _build_histogram(scores: list[int], bins: int = 10) -> list[dict]:
        """Build histogram data for D3 chart rendering."""
        if not scores:
            return []
        min_s, max_s = min(scores), max(scores)
        if min_s == max_s:
            return [{"bin_start": min_s, "bin_end": min_s + 10, "count": len(scores)}]

        bin_width = max(1, (max_s - min_s) // bins)
        histogram = []
        for i in range(bins):
            bin_start = min_s + i * bin_width
            bin_end = bin_start + bin_width
            count = sum(1 for s in scores if bin_start <= s < bin_end)
            if i == bins - 1:  # include max in last bin
                count = sum(1 for s in scores if bin_start <= s <= max_s)
            histogram.append({"bin_start": bin_start, "bin_end": bin_end, "count": count})
        return histogram

    @staticmethod
    def _get_caveats(match_state: str) -> list[str]:
        """Return relevant caveats based on match state."""
        caveats = [
            "Results are emergent outcomes from probabilistic simulation — not predictions.",
            "Player performance distributions are based on historical data and may not reflect current form.",
        ]
        if match_state == "FUTURE":
            caveats.insert(0, "CAUTION: Using probable XI — actual playing XI not yet confirmed.")
        return caveats

    def _empty_report(self, team1: str, team2: str, venue: str) -> dict[str, Any]:
        return {
            "disclaimer": DISCLAIMER,
            "simulation_id": self._simulation_id,
            "venue": venue,
            "teams": {"team1": team1, "team2": team2},
            "simulation_count": 0,
            "error": "No simulation results available",
        }

    async def generate_llm_narrative(
        self,
        report: dict[str, Any],
        team1: str,
        team2: str,
        winning_factors: list[dict[str, Any]] | None = None,
        hidden_factors: dict[str, Any] | None = None,
        simulation_mode: str = "hybrid",
    ) -> str | None:
        """
        Use the LLM to produce a rich narrative from simulation data + hidden factors.

        Called after generate_report() for ALL simulation modes (including probabilistic).
        Returns None only when LLM is disabled.
        """
        from ..services.llm_client import llm_client

        if not llm_client.is_enabled():
            return None

        win_prob = report.get("win_probability", {})
        score_dist = report.get("score_distribution", {})
        prediction = report.get("prediction", {})
        n_sims = report.get("simulation_count", 0)
        venue = report.get("venue", "Unknown")

        t1_wp = win_prob.get(team1, {})
        t2_wp = win_prob.get(team2, {})
        t1_sd = score_dist.get(team1, {})
        t2_sd = score_dist.get(team2, {})

        # Build hidden factors section
        hf_text = ""
        if hidden_factors:
            hf_parts = []
            if "dew_factor" in hidden_factors:
                hf_parts.append(f"Dew factor: {hidden_factors['dew_factor']:.2f} (1.0=dry, <0.85=significant dew)")
            if "boundary_asymmetry" in hidden_factors:
                ba = hidden_factors["boundary_asymmetry"]
                hf_parts.append(f"Boundary asymmetry: straight={ba.get('straight', 'N/A')}m, square={ba.get('square', 'N/A')}m")
            if "pitch_degradation" in hidden_factors:
                hf_parts.append(f"Pitch degradation: {hidden_factors['pitch_degradation']}")
            if "toss_advantage" in hidden_factors:
                hf_parts.append(f"Toss advantage: {hidden_factors['toss_advantage']}")
            if "pressure_peaks" in hidden_factors:
                hf_parts.append(f"High-pressure moments: {hidden_factors['pressure_peaks']}")
            if "ball_replacement_used" in hidden_factors:
                hf_parts.append(f"Ball replacement (2026 rule): {hidden_factors['ball_replacement_used']}")
            if hf_parts:
                hf_text = "\n\nHidden institutional factors from simulation:\n  " + "\n  ".join(hf_parts)

        # Build winning factors section
        wf_text = ""
        if winning_factors:
            wf_lines = [
                f"- {wf['factor']} ({wf['impact']} impact): {wf['detail']}"
                for wf in winning_factors[:5]
            ]
            wf_text = "\n\nKey winning factors from analysis:\n" + "\n".join(wf_lines)

        user_prompt = (
            f"Generate a comprehensive 4-paragraph match prediction report for {team1} vs {team2} at {venue}.\n\n"
            f"Engine: {simulation_mode} mode | {n_sims} parallel simulations\n\n"
            f"Win probabilities:\n"
            f"  {team1}: {t1_wp.get('win_pct', 0)}%  "
            f"(95% CI: {t1_wp.get('confidence_interval_95', {}).get('lower', 0)}–"
            f"{t1_wp.get('confidence_interval_95', {}).get('upper', 0)}%)\n"
            f"  {team2}: {t2_wp.get('win_pct', 0)}%  "
            f"(95% CI: {t2_wp.get('confidence_interval_95', {}).get('lower', 0)}–"
            f"{t2_wp.get('confidence_interval_95', {}).get('upper', 0)}%)\n\n"
            f"Score distributions:\n"
            f"  {team1}: mean {t1_sd.get('mean', 'N/A')}, median {t1_sd.get('median', 'N/A')}, "
            f"range {t1_sd.get('min', 'N/A')}–{t1_sd.get('max', 'N/A')}\n"
            f"  {team2}: mean {t2_sd.get('mean', 'N/A')}, median {t2_sd.get('median', 'N/A')}, "
            f"range {t2_sd.get('min', 'N/A')}–{t2_sd.get('max', 'N/A')}\n\n"
            f"Predicted winner: {prediction.get('winner')} "
            f"({prediction.get('confidence_label')} confidence, {prediction.get('confidence_pct')}%)"
            f"{hf_text}{wf_text}\n\n"
            "Generate 5–10 bullet points covering the systemic factors that drove the predicted winner's edge across all simulations.\n"
            "Focus areas: venue conditions (dew, pitch, boundary asymmetry), phase-wise dynamics (powerplay, middle, death), "
            "spin vs pace effectiveness, pressure cascades, toss value, home advantage, collapse risk, and any hidden factors "
            "that meaningfully shifted the win distribution.\n"
            "Do NOT name any players. Do NOT quote individual scores, sixes, strike rates, or bowling figures.\n"
            "Each bullet: name the factor → explain how it moved the needle → cite the number from the simulation data."
        )

        return await llm_client.think(
            system_prompt=(
                "You are the IPL Oracle ReportAgent — a cricket analytics AI synthesizing "
                "swarm simulation data into authoritative match previews. "
                "You have access to 50+ hidden institutional factors (dew, boundary asymmetry, "
                "pitch degradation, pressure peaks, ball replacement rule, collapse contagion, etc.) "
                "that feed into every agent's probability distributions. "
                "Be specific and bold. Reference the actual numbers. Keep it analytical but engaging.\n\n"
                "CRITICAL RULES:\n"
                "- This is an aggregate of 100 simulations. Do NOT mention individual player names.\n"
                "- Do NOT mention specific scores, sixes, bowling figures, strike rates, or single-simulation results.\n"
                "- Focus ONLY on the systemic factors, conditions, and dynamics that drove the winning team's "
                "advantage across all simulations (e.g., dew impact, pitch behavior, boundary asymmetry, "
                "pressure peaks, powerplay dynamics, death-over execution, spin vs pace effectiveness, "
                "home advantage, collapse probability, toss value).\n"
                "- Output as 5–10 concise bullet points. No paragraphs, no headings.\n"
                "- Each bullet should name one factor and explain how it shifted win probability with numbers."
            ),
            user_prompt=user_prompt,
            max_tokens=4096,
        )

    def __repr__(self) -> str:
        return f"ReportAgent(sim_id={self._simulation_id!r}, run_id={self._run_id[:8]!r})"
