"""
DisclaimerMiddleware — Injects X-IPL-Oracle-Disclaimer header on all /simulation/ routes.

This is a license requirement. Every simulation API response MUST include
the disclaimer header. The middleware also adds it to all /api/ routes.

Disclaimer text:
  "⚠️ SIMULATION ONLY: Generated by an AI swarm engine for research and entertainment.
   Not betting advice. Not a guarantee of outcomes.
   Repo owner accepts no responsibility for personal or financial losses.
   Full terms: LICENSE.md"
"""

from __future__ import annotations

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

DISCLAIMER_TEXT = (
    "SIMULATION ONLY: Generated by an AI swarm engine for research and entertainment. "
    "Not betting advice. Not a guarantee of outcomes. "
    "Repo owner accepts no responsibility for personal or financial losses. "
    "Full terms: LICENSE.md"
)

DISCLAIMER_ROUTES = ("/api/simulation/", "/api/schedule/", "/api/agents/")


class DisclaimerMiddleware(BaseHTTPMiddleware):
    """
    Starlette middleware that injects the IPL Oracle disclaimer header
    on all simulation, schedule, and agent API routes.

    The disclaimer is mandatory per the project license.
    It is added as the 'X-IPL-Oracle-Disclaimer' response header.
    """

    async def dispatch(self, request: Request, call_next) -> Response:
        response: Response = await call_next(request)

        path = request.url.path
        if any(path.startswith(route) for route in DISCLAIMER_ROUTES):
            response.headers["X-IPL-Oracle-Disclaimer"] = DISCLAIMER_TEXT
            response.headers["X-IPL-Oracle-Version"] = "4.0.0"
            response.headers["X-IPL-Oracle-Mode"] = "Week4-Hybrid-LLM"
            response.headers["X-IPL-Oracle-Warning"] = "NOT-BETTING-ADVICE"

        return response
